dirs:
  data_dir: data
  train_dir: train
  test_dir: test
  image_dir: images
  mask_dir: masks
  model_dir: models
  output_dir: output/maskdino_demo
  pred_mask_dir: predicted_masks
  pred_plot_dir: prediction_plots
  log_dir: logs
vars:
  train_log_name: maskdino_demo_train.log
  test_log_name: maskdino_demo_test.log
  log_level: "DEBUG"
  file_type: ".tif"
  patch_size: 256
  discard_rate: 0.95
  batch_size: 16 # Small batch for DETR-style model
  model_arch: "MaskDINO"
  model_name: trained_landcover_maskdino_detr_epochs3_patch256_batch2.pth
  encoder: "detr"
  encoder_weights: "imagenet"
  activation: "softmax2d"
  optimizer_choice: "AdamW"
  init_lr: 0.0001
  reduce_lr_by_factor: 0.5
  patience_epochs_before_reducing_lr: 5
  lr_reduce_threshold: 0.0001
  minimum_lr: 0
  epochs: 1
  device: "cpu"
  num_classes: 4
  all_classes: ["background", "building", "woodland", "water", "road"] # all the classes present in the dataset
  train_classes: ["building", "woodland", "water", "road"] # not training on 'road' class (need more fine-tuning)
  test_classes: ["building", "woodland", "water", "road"]