dirs:
  data_dir: data
  train_dir: train
  test_dir: test
  image_dir: images
  mask_dir: masks
  model_dir: models
  output_dir: output/maskdino_refined
  pred_mask_dir: predicted_masks
  pred_plot_dir: prediction_plots
  log_dir: logs

vars:
  train_log_name: maskdino_refined_train.log
  test_log_name: maskdino_refined_test.log
  log_level: "INFO"
  file_type: ".tif"

  patch_size: 256
  discard_rate: 0.9 # keep all 5 images
  batch_size: 4 # heavy model + tiny dataset
  num_workers: 0

  model_arch: "MaskDINO"
  model_name: "trained_landcover_maskdino_refined.pth"
  encoder: "detr"
  encoder_weights: "imagenet"
  activation: "softmax2d"
  is_transformer: true

  optimizer_choice: "AdamW"
  init_lr: 0.00005 # lower for stability
  weight_decay: 0.01
  betas: [0.9, 0.999]
  reduce_lr_by_factor: 0.5
  patience_epochs_before_reducing_lr: 3
  lr_reduce_threshold: 0.001
  minimum_lr: 0.000001
  warmup_epochs: 1
  epochs: 30 # enough to overfit 5 images
  gradient_clip_value: 1.0
  use_amp: True # disable AMP for simplicity
  grad_accum_steps: 1
  dropout: 0.0
  label_smoothing: 0.0
  device: "cuda"
  num_classes: 4
  all_classes: ["background", "building", "woodland", "water", "road"] # all the classes present in the dataset
  train_classes: ["building", "woodland", "water", "road"] # not training on 'road' class (need more fine-tuning)
  test_classes: ["building", "woodland", "water", "road"]
